version: '3'

services:
  db-test:
    image: postgres
    hostname: db-service
    networks:
      - network-test
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local/test/progresql-data:/var/lib/postgresql/data/

  migrate-test:
    depends_on:
      - db-test
    image: migrate/migrate
    networks:
      - network-test
    volumes:
      - ./migrations:/migrations
    command: -database postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable -path /migrations up
    restart: on-failure

  user-test:
    depends_on:
      - migrate-test
    build:
      context: .
      dockerfile: Dockerfile.user
    hostname: go-user-service
    networks:
      - network-test
    ports:
      - "4001:4001"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - DBDSN=${DBDSN:-postgres://postgres:postgres@db-service:5432/postgres?sslmode=disable}
      - AUTHSECRET=${AUTHSECRET:-secret}
    deploy:
      restart_policy:
        condition: on-failure

networks:
  network-test:
    driver: bridge