# Get Golang 1.17
FROM golang:1.17-alpine

# Get e-inwork.com Golang User Microservice
RUN go get -u github.com/e-inwork-com/golang-user-microservice/cmd

# Expose port
EXPOSE 4000

# Run Microservice
CMD ["cmd"]
